apiVersion: v1
kind: Secret
metadata:
    name: oidc-cred
    namespace: apps
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    clientId: ENC[AES256_GCM,data:iXJ0Padn,iv:CPNo9j+7k8rF2ctEK4RxcIsMNIvTHxXN1AmU6UCKDF4=,tag:asvt+YZyV7bcv0E7JiYO5g==,type:str]
    clientSecret: ENC[AES256_GCM,data:cXwYWujY15Df+DOaQtGKkq+z/jf8vC0bIXqTxrg16D4=,iv:qDZ5HJ1oHA8EJnL+W4y/7fBgZd7VTs/LQVB77IGHxhM=,tag:rWjL1VXoT6BH8eu8OnXBpw==,type:str]
sops:
    age:
        - recipient: age1x2rf994rywsausfypcwmhhfv6zjd97995jssp9vy379p8zj925zqm0d6r0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUHI4WndrUTdDWnFXYlhY
            dXZIVmk1bDhCZEwrNmZZMFVRODU0R1R4SkFRCndhUC9GSFhvQ3A5UnZvRGFTRTNF
            OHRuUndBOXluVmRqOS9rRFRqZVoyUkEKLS0tIDRpN3lOdi9vdUxVNW5FN0JYcEc3
            UGVWZG16bXpWS2lGQjlFQU1DUnFJOEUKkyuORGWM4emWJhpfhOxlVysX36EaYrpP
            N91Y+nVG/Kznq2K20UR4wFasOZGxQgYrxtPOcEc/UIFjcj6meMzkjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T13:15:55Z"
    mac: ENC[AES256_GCM,data:td4Mn9qfJNqq2Iayo+WAvOamXFn/YtbDs9j+3SmQXj5ru/CNu3kqTVt5wGgrBA3p0HxCXX3kBQyuWZbhlw3GRuUoJS0GwKG3sDunJFAgPbFubkeIOuUQTn5fwegPfaJYUhGGSg8aFL+0YeDsIvnN85il59j+ea4d8KHQbGLFiqc=,iv:dV7/mvU71ARXZKpB21GoMPukvuxy8ZdzW7LG0SpNMs4=,tag:Yef5vcFG7TgOnCg0HB0lPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
