### hubapim
---    
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hubapim
  namespace: argocd
spec:
  project: default
  source:
    path: hubapim
    repoURL: https://github.com/NEwa-05/argo-dependencies-test.git
    targetRevision: localdemo
  destination:
    server: 'https://kubernetes.default.svc'