apiVersion: v1
kind: Secret
metadata:
    name: oidc-cred
    namespace: apps
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    clientId: ENC[AES256_GCM,data:vUjx7TDd,iv:es6smbdIjmRNPb3wmmTXfjsHfL1qcza1UUBEWw6Ms3w=,tag:pYiPO6gGvSrUKVUyKyRLQQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:qX4qrUlnruxoCD5uHLMvvzcqpu5WhiflMKeNB6Sr9iA=,iv:v7qY7yGkqrPwTSssxYeC9GT5DZUVM4kctBpEFzxI79A=,tag:J/q63oTLzrx7UCr7LpppAQ==,type:str]
sops:
    age:
        - recipient: age1x2rf994rywsausfypcwmhhfv6zjd97995jssp9vy379p8zj925zqm0d6r0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZVB1QmZpUWhwZXE4b0Ru
            aHBRZHpUTlJkYzZSYnp1MmJueHRYcmM5UDFRClg2VGJlbjcyTjFCSE90TXZWeXlG
            VGplSTg1ZDBueVVnZ2tvSk1tdDZ5ME0KLS0tIDF5NzRvY1luQ3dORDBFUERnYTZ6
            S0QzTXp4OHJmelR6TzdxUk5xakVXS28K2B5tKdGbGFGXC3JAbieq+5Qcc+4bmY/S
            /R9PtfZOGum0lAazADQwxnxJZtLVSL40qUxSWmN/0yEfAejVgW9eEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T13:15:55Z"
    mac: ENC[AES256_GCM,data:dsNG8leAqTfcnbGJTD19gUQqKQ/72pbGpebo3xzNYdM1XyOn7U7DaFdnh5KQyu1E9lPmvp5QDgDLcJVs6cwu1MH6xnlI0KVgUijexEuN5gnkGbRLmJiyUnjDv2cnUSsQWa0ilBZJ+kIUTmhmL4YzxDJe6xWK0FwfVDYiddTocoY=,iv:gvHwAKoJxvBuxKbaxdVzTZEhFyVFfc/McnMrhcUaNxs=,tag:0OfAdb03vwBmtNa0lIO3Tg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
