---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-cred
  namespace: apps
  annotations:
    kustomize.config.k8s.io/behavior: replace
stringData:
  clientId: ${PORTAL_CLIENTID}
  clientSecret: ${PORTAL_CLIENTSEC}